server:
  port: 8001
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # show_sql은 system out으로 로깅, 실행 환경에서는 로거를 통해 로깅을 활성화 하자.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # 로거를 통해 로깅 활성화

